services:
  backend:
    build:
      context: ./src/backend  
      dockerfile: Dockerfile
    container_name: crypto_backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app  
    networks:
      - crypto_network

  frontend:
    build:
      context: ./src/frontend  
      dockerfile: Dockerfile
    container_name: crypto_frontend
    ports:
      - "3000:80"
    volumes:
      - ./src/frontend:/app  
    environment:
      - NODE_ENV=production
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge
